---

- name: Create jupyterhub user random password
  set_fact:
    random_pwd: "{{ lookup('password', '/dev/null length=20') }}"

- name: Change jupyterhub password
  user:
    name: "{{ username }}"
    password: "{{ random_pwd | string |  password_hash('sha512') }}"
    update_password: always

- name: 'Save password on file. TODO: Move to Vault'
  copy:
    content: '{{ random_pwd }}'
    dest: '/home/{{ username }}/pssw.txt'
    owner: "{{ username }}"
    group: "{{ username }}"