---

- name: Create jupyterhub user random password
  set_fact:
    random_pwd: "{{ lookup('password', '/dev/null length=20') }}"
  no_log: True
  when: not retrieve_passphrase_from_vault

- name: Update jupyterhub user password
  user:
    name: "{{ username }}"
    password: "{{ random_pwd | string |  password_hash('sha512') }}"
    update_password: always
  no_log: True
  when: not retrieve_passphrase_from_vault

- name: Save password on file.
  copy:
    content: '{{ random_pwd }}'
    dest: '/home/{{ username }}/pssw.txt'
    owner: "{{ username }}"
    group: "{{ username }}"
  no_log: True
  when: not retrieve_passphrase_from_vault

- name: Create JupyterHub user and set jupiterhub user password from Vault
  user:
    name: "{{ username }}"
    state: present
    password: "{{ vault_secrets.data.admin_password | string | password_hash('sha512') }}"
    update_password: on_create
  no_log: True
  when: retrieve_passphrase_from_vault
